### ISSUE TITLE
[Question] API to let other extensions know theme color has changed

### ISSUE THREAD

**Issue by Depau** [nt1m/vivaldi-fox#74] opened 2018-03-18 21:08 UTC
See this issue: https://github.com/freaktechnik/advanced-github-notifier/issues/81

Is there some API other extensions can use to detect whether toolbar icons should be displayed in white or black?

**Comment by nt1m** [comment] 2018-04-12 14:56
Duplicate of #59 

This should hopefully be solved with https://bugzilla.mozilla.org/show_bug.cgi?id=1441708 fixed

**Closed by nt1m** 2018-04-12 14:56 UTC
Labels: needs-webextension-api
