### ISSUE TITLE
[Feature] Show colors on unfocused tabs

### ISSUE THREAD

**Issue by dull-bird** [nt1m/vivaldi-fox#116] opened 2020-10-19 13:45 UTC
Would it be possible to show colors on unfocused tabs? I guess this is good for people to switch tabs based on some "color memory".

Thanks!

**Comment by nt1m** [comment] 2020-10-19 15:20
Duplicate of #9 :) Unfortunately not feasible atm.

**Closed by nt1m** 2020-10-19 15:20 UTC
