### ISSUE TITLE
[Feature] Alpha/Transparent colors

### ISSUE THREAD

**Issue by danimesq** [nt1m/vivaldi-fox#101] opened 2018-11-11 21:03 UTC
Also, option to use OS default window style

**Comment by DaniellMesquita** [comment] 2018-11-11 22:07
Support to apply transparency to other places, such as browser window

**Comment by nt1m** [comment] 2021-11-09 10:18
Duplicate of #121

**Closed by nt1m** 2021-11-09 10:18 UTC

**Comment by danimesq** [comment] 2021-11-09 15:57
@nt1m, you meant, #121 is the duplicate of this issue.
