### ISSUE TITLE
Fallback when favicon is not available

### ISSUE THREAD

**Issue by Rictusempra** [nt1m/vivaldi-fox#50] opened 2017-11-08 05:31 UTC
- Firefox logo color scheme
- website background color scheme
- users specific in RGB expression

**Comment by nt1m** [comment] 2017-11-09 15:50
Duplicate of #8

**Closed by nt1m** 2017-11-09 15:50 UTC

**Comment by Rictusempra** [comment] 2017-11-10 01:22
@nt1m I don't think that is much dup.
Since #8 only match case 3 here.
